- name: build list of leafs and spines
  hosts: localhost
  tasks:
    - name: Read in deets.yml
      include_vars:
        file: schema.yml
        name: config

    - name: build device list from deets.yml and 1buildInventory.j2
      template:
        src: 1buildInventory.j2
        dest: sample_inventory_from_1buildInventory.yml
