devs:
  leafs:
    number: 6
    base_name: Leaf
    base_mgmt_ip: 192.168.10.70
    uplinks:
      num: 2
      iface: 
        - eth1
        - eth2
      
  spines:
    number: 2
    base_name: Spine
    base_mgmt_ip: 192.168.10.80
global:
  ipv4:
    loopback: 10.255.0.0
    uplinks: 10.0.0.0
    
    